### ISSUE TITLE
ThemeInterfacer has stopped (i9300)

### ISSUE THREAD

**Issue by zatherz** [LineageOMS/merge_script#4]
I ran this script on top of fresh lineage sources for i9300. "ThemeInterfacer has stopped (i9300)" appears soon after boot or when I run substratum.  Substratum itself fails to install the Swift Dark. The error log shows a list of things that failed to install with only the text `"(Exception) ` (verbatim) after each entry.

Note: I'm not sure if this is the right place to post this, because I don't know what's actually at fault (OMS? the cherrypicked code?).

**Comment by nathanchance** [comment]
@zatherz when did you last build? There should be no issues with Interfacer after https://github.com/LineageOMS/android_system_sepolicy/commit/3eb208437d20fc016a9d0c17cc134ea76d06ab5a, which was pushed 13 hours ago.

**Comment by zatherz** [comment]
Oh my god, lol. I synced and merged yesterday. Let me try that again.

**Comment by zatherz** [comment]
That was it. Thanks for the quick response.
