### ISSUE TITLE
Failed merging packages/apps/Settings and vendor/cm on S4 International LTE (jfltexx)

### ISSUE THREAD

**Issue by zatherz** [LineageOMS/merge_script#5]
[Script output](https://pastebin.com/x0iaud3v)

**Comment by nathanchance** [comment]
I'm not doing anything with these repos until Oreo is up and running.

**Comment by zatherz** [comment]
Makes sense.

**Comment by zatherz** [comment]
I tried to resolve the two conflicts manually (both of which affect just one file each). In the `packages/apps/Settings` conflict I chose the second variant (from the LineageOMS commit) and in the `vendor/cm` conflict I chose the first option (it's blank, which means that afterwards you have to `git commit --allow-empty` and only then can you `git cherry-pick --continue`). 

Now building, will update later. If this works it should be useful for anybody else who stumbles upon this issue (but note that this way is obviously unofficial, even if it does work).

**Comment by zatherz** [comment]
It works! Here are the steps:

* Run the merge script, you should get conflicts in `packages/apps/Settings` and `vendor/cm`

* `cd` to `packages/apps/Settings`

* Open the file `src/com/android/settings/deviceinfo/StorageSettings.java` in a text editor and resolve the merge conflict by picking the second variant.

* Run `git add -A` to stage all the files

* Run `git cherry-pick --continue` to let it finish the cherry picking - no merges here should fail

* Go back to your Lineage build root

* Go to `vendor/cm`

* Open the file `sepolicy/mac_permissions.xml` in a text editor and resolve the merge conflict by picking the first variant.

* Run `git add -A` to stage all files.

* Run `git commit --allow-empty` to commit the empty change (you can't continue with the cherry pick otherwise)

* Run `git cherry-pick --continue` to finish the cherry picking - no merges here should fail

* Go back to the Lineage build root

* Continue building as normal
